# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d1a9360582c7039d9496279931bdafa9ae44ab18dee3cc76bcc0cad21bbd1b53d691d38c4d060c23b8fc4c267c1dd4cba99b0fe4cbf6025c607d48673138bad

test:
  secret_key_base: 279b5923fb442d49fe8d542f44c376bd2b41f95a8bb0e283960178ed9b934e4556be4709f3377e151f91b5e64f4be24d7fa831efd002123ad0a42e58d5ee2e88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
